config/routes.rb
Rails.application.routes.draw do
  resources :room, only: [:create, :show] do
    resources :participant, only: [:new, :create]
    resources :round, only: [:create] do
      resources :vote, only: [:create]

      member do
        post :reset
        post :unseal
      end
    end

    member do
      get :current_standing
      get :join
    end
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :room
  has_many :votes

  scope :connected, -> { where(connected: true) }
  scope :voted, -> (round_id) { where(id: Vote.where(round_id: round_id).select(:participant_id)) }

  after_create :broadcast_new_participant
  after_update :broadcast_new_participant

  def vote_for_round(round_id)
    votes.for_round(round_id).take
  end

  private

  def broadcast_new_participant
    VoteChannel.broadcast_new_participant(self)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :rounds
  has_many :participants

  def current_round
    self.rounds.latest
  end
end

app/models/room_hash_service.rb
class RoomHashService
  attr_accessor :room_id, :participant_id

  def initialize(room_id, participant_id)
    @participant_id = participant_id
    @room_id = room_id
  end

  def self.from_hash(hash_str)
    object = JSON.parse(Base64.urlsafe_decode64(hash_str))

    RoomHashService.new(
      object['room']&.to_i,
      object['participant']&.to_i
    )
  end

  def hash
    Base64.urlsafe_encode64({
      participant: @participant_id,
      room: @room_id
    }.to_json)
  end
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :room
  has_many :votes

  after_create :broadcast_new_round

  def self.latest
    order(:created_at).last
  end

  private

  def broadcast_new_round
    VoteChannel.broadcast_new_round(self)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :participant
  belongs_to :round
  has_one :room, through: :round

  scope :for_round, -> (round_id) { where(round_id: round_id) }

  after_create :broadcast_new_vote
  after_update :broadcast_new_vote

  def human_choice
    choice&.[]('value')
  end

  private

  def broadcast_new_vote
    VoteChannel.broadcast_new_vote(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/participant_controller.rb
class ParticipantController < ApplicationController
  before_action :set_room

  def new
    # pass
  end

  def create
    participant = Participant.create(
      room_id: @room.id,
      name: params[:name]
    )

    redirect_to(
      room_path(
        RoomHashService.new(@room.id, participant.id).hash
      )
    )
  end

  private

  def set_room
    @room_hash = RoomHashService.from_hash(params[:room_id])
    @room = Room.find_by_id(@room_hash.room_id)
  end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
  before_action :set_room, only: [:show, :current_standing]
  before_action :set_connected, only: [:show]

  def create
    room = Room.create(
      name: params[:name]
    )

    redirect_to (
      new_room_participant_path(
        RoomHashService.new(room.id, nil).hash
      )
    )
  end

  def join
    redirect_to new_room_participant_path(params[:id])
  end

  def show
    # pass
  end

  def current_standing
    render partial: 'current_standing', locals: { room: @room, participant: @participant, round: @round }, layout: false
  end

  private

  def set_room
    @room_hash = RoomHashService.from_hash(params[:id])
    @room = Room.find_by_id(@room_hash.room_id)
    @round = @room.current_round
    @participant = Participant.find_by_id(@room_hash.participant_id)
  end

  def set_connected
    @participant.update_attribute(:connected, 1)
  end
end

app/controllers/round_controller.rb
class RoundController < ApplicationController
  before_action :set_room, only: [:create, :reset, :unseal]
  before_action :set_round, only: [:reset, :unseal]

  def create
    round = Round.create(
      room_id: @room.id,
      description: params[:description]
    )

    render json: { round_id: round.id }
  end

  def reset
    round = Round.create(
      room_id: @round.room_id,
      description: @round.description
    )

    render json: { round_id: round.id }
  end

  def unseal
    @round.votes.each do |vote|
      vote.update_attribute(:sealed, false)
    end

    render json: {}
  end

  private

  def set_room
    @room_hash = RoomHashService.from_hash(params[:room_id])
    @room = Room.find_by_id(@room_hash.room_id)
    @participant = Participant.find_by_id(@room_hash.participant_id)
  end

  def set_round
    @round = Round.find_by_id(params[:id])
  end
end

app/controllers/vote_controller.rb
class VoteController < ApplicationController
  before_action :set_room
  before_action :set_round

  def create
    vote =
      Vote.transaction do
        vote = Vote.find_or_create_by(
          participant_id: @participant.id,
          round_id: @round.id
        )
        vote.update(
          choice: { value: params[:choice] },
          sealed: true
        )
        vote
      end

    render json: { vote_id: vote.id }
  end

  private

  def set_room
    @room_hash = RoomHashService.from_hash(params[:room_id])
    @room = Room.find_by_id(@room_hash.room_id)
    @participant = Participant.find_by_id(@room_hash.participant_id)
  end

  def set_round
    @round = Round.find_by_id(params[:round_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/participant_helper.rb
module ParticipantHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/round_helper.rb
module RoundHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/home/index.html.erb
<% content_for :stylesheets do %>
  <% stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class='panel create-room'>
  <div class='title'>Create new room</div>
  <%= form_with url: room_index_path, method: :post do |form| %>
    <%= form.label :name, 'Name' %>
    <%= form.text_field :name, autofocus: 'autofocus' %>
    <%= form.submit "Create" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-id="<%= params[:id] %>">
  <head>
    <title>Scrum p0k3r</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= yield :stylesheets %>
    <%= yield :scripts %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/participant/new.html.erb
<% content_for :stylesheets do %>
  <% stylesheet_link_tag 'participant', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class='join-room panel'>
  <div class='title'><%= @room.name %></div>
  <%= form_with url: room_participant_index_path(@room_hash.hash), method: :post do |form| %>
    <%= form.label :name, 'Your Name' %>
    <%= form.text_field :name, autofocus: 'autofocus' %>
    <%= form.submit "Join" %>
  <% end %>
</div>

app/views/room/_current_standing.html.erb
<p>
  Votes for all participants that are either currently online, or has already
  cast a vote in this round.
</p>

<table>
  <thead>
    <tr>
      <th>
        Participant
      </th>
      <th>
        Choice
      </th>
    </tr>
  </thead>
  <tbody>
    <% connected = room.participants.connected %>
    <% voted = room.participants.voted(round.id) %>
    <% participants = voted.or(connected) %>
    <% participants.order(:name, :id).each do |participant| %>
      <tr data-participant-id='<%= participant.id %>'>
        <td>
          <%= participant.name %>
          <% if !participant.connected? %>
            <span class='connection-status'>(disconnected)</span>
          <% end %>
        </td>
        <td>
          <% vote = participant.vote_for_round(round.id) %>
          <% if vote&.sealed? %>
            <span class='sealed'>Sealed</span>
          <% else %>
            <%= vote&.human_choice %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/room/show.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'room', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<% content_for :scripts do %>
  <%= javascript_pack_tag 'room' %>
<% end %>

<div class='flex-container column'>
  <div class='greeting panel'>
    <div class='title'><%= @room.name %></div>

    <p>
      Hello <%= @participant&.name %>! You can invite additional participants with the following URL:
    </p>

    <div class='flex-container'>
      <input type='text' class='flex' value='<%= join_room_url(RoomHashService.new(@room.id, nil).hash) %>'>
    </div>
  </div>

  <% if @round %>
    <div class='flex-container row'>
      <div class='vote-machine panel'>
        <p>
          <%= @round.description %>
        </p>
        <div class='card-container'>
          <% ['?', 1, 2, 3, 5, 7, 8, 11, 13, 17, 21].each do |value| %>
            <%= form_with url: room_round_vote_index_path(@room_hash.hash, @round.id), action: :post, html: { "data-remote" => true } do |form| %>
              <%= form.hidden_field :choice, id: nil, value: value %>
              <%= form.submit(value, class: 'card') %>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class='current-standing panel' id='current-standing-panel' data-refresh-url='<%= current_standing_room_path(@room_hash.hash) %>'>
        <%= render partial: 'current_standing', locals: { room: @room, round: @round, participant: @participant } %>
      </div>
    </div>

    <div class='round-control panel'>
      <div class='flex-container row'>
        <div class='flex align-center'>
          <%= form_with url: reset_room_round_path(@room_hash.hash, @round.id), action: :post, html: { "data-remote" => true } do |form| %>
            <p class='tip'>
              Remove all votes from the current round.
            </p>
            <%= form.submit 'Reset' %>
          <% end %>
        </div>
        <div class='flex align-center'>
          <%= form_with url: unseal_room_round_path(@room_hash.hash, @round.id), action: :post, html: { "data-remote" => true } do |form| %>
            <p class='tip'>
              Make all votes visible to all participants.
            </p>
            <%= form.submit 'Unseal' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <div class='panel'>
    <p>
      In order to start voting on a new story enter a short description in the
      text area below and press the <i>Create New Round</i> button. Any active
      participants will automatically see the new story and be able to vote. Any
      votes will be <i>sealed</i> until manually unsealed.
    </p>
    <%= form_with url: room_round_index_path(@room_hash.hash), action: :post, html: { "data-remote" => true } do |form| %>
      <%= form.label :description, 'Description' %>
      <div class="flex-container">
        <%= form.text_area :description, size: '80x4', class: 'flex' %>
      </div>
      <div class='align-right'>
        <%= form.submit 'Create New Round' %>
      </div>
    <% end %>
  </div>
</div>